// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2025 Matt Geiger, Temple Consulting, LLC.
//
// LOTTO — Line Order Transparency & Ticketing Organizer. Application code
// licensed under AGPL-3.0-or-later; see LICENSE. William Temple House branding
// is not covered by this license; see TRADEMARKS.md.

// Canonical English UI strings. Kept in a plain (non-"use client") module so
// both the language context (client) and the AI translation engine (server) can
// import the source set without crossing the client boundary.

export const UI_STRINGS_EN: Record<string, string> = {
    nowServing: "Now Serving",
    arcadeEstimatedWaitLabel: "ESTIMATED WAIT",
    arcadeTicketCalledTitle: "TICKET CALLED!",
    arcadePleaseCheckIn: "PLEASE CHECK-IN",
    ticketCalledTitle: "Ticket Called!",
    ticketCalledCheckIn: "Please Check-in",
    waiting: "Pending",
    foodPantryServiceFor: "Food Pantry Service For",
    currentTime: "Current Time",
    ticketsIssuedToday: "Ticket Numbers Issued Today",
    totalTicketsIssued: "Total Tickets Issued",
    drawingOrder: "Drawing Order",
    updated: "Updated",
    welcome: "Welcome!",
    raffleNotStarted: "The raffle has not yet started.",
    checkBackSoon: "Check back soon for updates.",
    pantryClosed: "Pantry Closed Today",
    nextOpenDay: "Next Open",
    pantryHours: "Pantry Hours",
    pantryNotOpenYet: "Pantry Has Not Opened Yet",
    pantryClosedForDay: "Pantry Has Closed For The Day",
    todaysHours: "Today's Hours",
    closed: "CLOSED",
    sunday: "Sunday",
    monday: "Monday",
    tuesday: "Tuesday",
    wednesday: "Wednesday",
    thursday: "Thursday",
    friday: "Friday",
    saturday: "Saturday",
    pollingState: "Polling for latest state…",
    refreshing: "Refreshing…",
    lastChecked: "Last checked",
    errorLoadingState: "Error loading state",
    unknownError: "Unknown error",
    ticket: "Ticket",
    queuePosition: "Queue Position",
    ticketsAhead: "Tickets Ahead",
    estimatedWait: "Estimated Wait",
    notCalled: "Not called",
    called: "Called",
    unclaimed: "Unclaimed",
    returned: "Returned",
    returnedTicketMessage:
      "This ticket number is marked as \"Returned\" and will not be called. Is this your ticket? Please let staff know about this issue.",
    unclaimedTicketMessage:
      "This ticket number has been called but is still unclaimed. If this is your ticket, please check-in or speak with a member of our staff.",
    calledAtMessage: "This ticket was called at",
    close: "Close",
    ticketNotFoundTitle: "Ticket not found",
    ticketNotFoundMessage: "Ticket number not found! Please check your ticket and try again.",
    searchButtonLabel: "Submit",
    searchTicketLabel: "Enter your ticket number",
    searchTicketPlaceholder: "ENTER TICKET #",
    yourTicketCardTitle: "YOUR TICKET",
    yourTicketNumberLabel: "YOUR TICKET NUMBER",
    yourEstimatedWaitLabel: "YOUR ESTIMATED WAIT TIME",
    ticketsAheadOfYouLabel: "TICKETS AHEAD OF YOU",
    yourTicketPositionLabel: "YOUR TICKET'S POSITION",
    checkBackSoonValue: "CHECK BACK SOON",
    ticketNotInDrawingYetMessage: "Your ticket number is not yet in the drawing. Check back soon.",
    changeTicket: "Enter a new ticket number",
    viewInventory: "See what's in stock",
    inventoryPageTitle: "What's in stock today",
    inventorySearchPlaceholder: "Search inventory",
    inventoryResultsLabel: "Inventory results",
    visitArcade: "PLAY GAMES",
    navTicket: "Your ticket",
    navDashboard: "Dashboard",
    navInventory: "What's in stock",
    navGames: "Games",
    navAdmin: "Admin",
    navPrimaryLabel: "Primary navigation",
    inventoryDietaryFilterLabel: "Dietary filters",
    inventoryClearFilters: "Clear filters",
    chooseLanguage: "Choose your language",
    ticketFormatHint: "Use a ticket like C17 or 17.",
    drawingNotStartedHint: "The drawing hasn't started yet — enter your number and we'll save it for today.",
    justBrowsing: "I'm just looking",
    announcementContinue: "Continue",
    inventoryUpdatedLabel: "Updated:",
    inventoryItemsLabel: "items",
    inventoryColumnItem: "Item",
    inventoryColumnLimit: "Limit",
    inventoryColumnStatus: "Status",
    inventoryColumnDietary: "Dietary",
    inventoryLimitPerHousehold: "Limit {count} per household",
    inventoryLimitPerPerson: "Limit {count} per person",
    // Arcade
    arcadeGames: "Arcade Games",
    back: "BACK",
    selectGame: "Select Game",
    snakeTitle: "Snake",
    moreGamesComing: "More Games Coming Soon",
    playSnake: "PLAY SNAKE",
    snakeInstructionMove: "USE ARROWS TO MOVE",
    snakeInstructionPoints: "EAT PELLETS FOR POINTS",
    snakeInstructionGrow: "EATING MAKES YOU GROW",
    snakeInstructionAvoid: "AVOID WALLS AND YOUR BODY",
    snakeInstructionCrash: "CRASHING ENDS THE GAME",
    playNow: "PLAY NOW",
    reset: "RESET",
    start: "START",
    play: "PLAY",
    pause: "PAUSE",
    gameOverCollision: "GAME OVER: COLLISION DETECTED",
    gameOver: "GAME OVER",
    tapToPlayAgain: "TAP HERE TO PLAY AGAIN",
    score: "SCORE",
    length: "LENGTH",
    lives: "LIVES",
    level: "LEVEL",
    snakeSpeedLabel: "SPEED",
    snakeDifficultyLabel: "DIFFICULTY",
    snakeDifficultySettingTitle: "DIFFICULTY SETTING",
    snakeSettingLabel: "SETTING",
    snakeSpeedSlow: "SLOW",
    snakeSpeedNormal: "NORMAL",
    snakeSpeedFast: "FAST",
    snakeDifficultyEasy: "EASY",
    snakeDifficultyMedium: "MEDIUM",
    snakeDifficultyHard: "HARD",
    snakeModeVeryEasy: "VERY EASY",
    snakeModeEasy: "EASY",
    snakeModeNormal: "NORMAL",
    snakeModeHard: "HARD",
    snakeModeVeryHard: "VERY HARD",
    snakeModeNightmare: "NIGHTMARE",
    gameOverAnnouncement: "Game over.",
    arcadeHighScoresTitle: "TOP 10 SCORES",
    arcadeHighScoresLoading: "LOADING SCORES",
    arcadeHighScoresEmpty: "NO SCORES YET",
    arcadeHighScoresUnavailable: "SCORES UNAVAILABLE",
    arcadeHighScoreQualify: "NEW TOP 10! ENTER INITIALS",
    arcadeHighScoreInitialsLabel: "3 INITIALS",
    arcadeHighScoreSubmit: "SAVE",
    arcadeHighScoreTimer: "{seconds}s LEFT",
    arcadeHighScoreExpired: "ENTRY TIME EXPIRED",
    arcadeHighScoreSaved: "SCORE SAVED",
    arcadeHighScoreRejected: "SCORE DID NOT QUALIFY",
    arcadeHighScoreSaveError: "COULD NOT SAVE SCORE",
    // Brick Mayhem
    brickMayhemTitle: "Brick Mayhem",
    brickMayhemDifficultySettingTitle: "DIFFICULTY SETTING",
    brickMayhemSettingLabel: "SETTING",
    brickMayhemInstructionPaddle: "USE THE SLIDER TO MOVE",
    brickMayhemInstructionStrike: "HIT BRICKS WITH THE BALL",
    brickMayhemInstructionDrop: "DON'T DROP THE BALL!",
    brickMayhemInstructionClear: "CLEAR A PATH TO THE TOP",
    brickMayhemInstructionTop: "GET THE BALL TO THE TOP!",
    brickMayhemBallsLabel: "BALLS",
    brickMayhemEffectsLabel: "EFFECTS",
    brickMayhemEffectClone: "CLONE",
    brickMayhemEffectWidePaddle: "PADDLE x2",
    brickMayhemEffectTriplePoints: "POINTS x3",
    // Zombie Attack!
    zombieAttackTitle: "Day of the Dead",
    zombieAttackDifficultySettingTitle: "DIFFICULTY SETTING",
    zombieAttackSettingLabel: "SETTING",
    zombieAttackInstructionMove: "USE SLIDER TO MOVE",
    zombieAttackInstructionFire: "HOLD A TO FIRE",
    zombieAttackInstructionDefend: "PROTECT THE FENCE FROM ZOMBIES",
    zombieAttackInstructionBub: "SHOOT AMBULANCES AND GRENADES FOR A BLAST",
    zombieAttackInstructionHeli: "SURVIVE EACH ROUND TO EXTRACT THE CHOPPER",
    zombieAttackRound1: "CLEAR THE PAD — CHOPPER INBOUND",
    zombieAttackRound2: "REFUELING — HOLD THE LINE",
    zombieAttackRound3: "BOARDING — PROTECT THE CHOPPER",
    zombieAttackRound4: "TAKEOFF — COVER THE LIFT-OFF",
    zombieAttackExtractionComplete: "EXTRACTION COMPLETE!",
    zombieAttackRoundLabel: "ROUND",
    zombieAttackTimeLabel: "TIME",
    language: "Language",
    haptics: "Haptics",
    hapticsOn: "Haptics on",
    hapticsOff: "Haptics off",
    inventoryStatusLimited: "Limited Supply",
    inventoryStatusClearance: "Clearance",
    inventoryDietaryGlutenFree: "Gluten-free",
    inventoryDietaryVegan: "Vegan",
    inventoryDietaryVegetarian: "Vegetarian",
    inventoryDietaryHalal: "Halal",
    inventoryDietaryKosher: "Kosher",
    inventoryDietaryOrganic: "Organic",
    inventoryDietaryReadyToEat: "Ready to eat",
};
