"use client";

import React from "react";

export type Language = "en" | "zh" | "es" | "ru" | "uk" | "vi" | "fa" | "ar";

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
};

const LanguageContext = React.createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = React.useState<Language>("en");

  React.useEffect(() => {
    const stored = typeof window !== "undefined" ? localStorage.getItem("display-language") : null;
    if (stored && ["en", "zh", "es", "ru", "uk", "vi", "fa", "ar"].includes(stored)) {
      setLanguageState(stored as Language);
    }
  }, []);

  const setLanguage = React.useCallback((lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== "undefined") {
      localStorage.setItem("display-language", lang);
    }
  }, []);

  const t = React.useCallback(
    (key: string) => translations[language]?.[key] ?? translations.en[key] ?? key,
    [language],
  );

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = React.useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    nowServing: "Now Serving",
    waiting: "Pending",
    foodPantryServiceFor: "Food Pantry Service For",
    ticketsIssuedToday: "Ticket Numbers Issued Today",
    totalTicketsIssued: "Total Tickets Issued",
    drawingOrder: "Drawing Order",
    updated: "Updated",
    welcome: "Welcome!",
    raffleNotStarted: "The raffle has not yet started.",
    checkBackSoon: "Check back soon for updates.",
    pantryClosed: "Pantry Closed Today",
    nextOpenDay: "Next Open",
    pantryHours: "Pantry Hours",
    pantryNotOpenYet: "Pantry Has Not Opened Yet",
    pantryClosedForDay: "Pantry Has Closed For The Day",
    todaysHours: "Today's Hours",
    closed: "CLOSED",
    sunday: "Sunday",
    monday: "Monday",
    tuesday: "Tuesday",
    wednesday: "Wednesday",
    thursday: "Thursday",
    friday: "Friday",
    saturday: "Saturday",
    pollingState: "Polling for latest state…",
    refreshing: "Refreshing…",
    lastChecked: "Last checked",
    errorLoadingState: "Error loading state",
    unknownError: "Unknown error",
    ticket: "Ticket",
    queuePosition: "Queue Position",
    ticketsAhead: "Tickets Ahead",
    estimatedWait: "Estimated Wait",
    notCalled: "Not called",
    called: "Called",
    unclaimed: "Unclaimed",
    returned: "Returned",
    returnedTicketMessage:
      "This ticket number is marked as \"Returned\" and will not be called. Is this your ticket? Please let staff know about this issue.",
    unclaimedTicketMessage:
      "This ticket number has been called but is still unclaimed. If this is your ticket, please check-in or speak with a member of our staff.",
    calledAtMessage: "This ticket was called at",
    close: "Close",
    ticketNotFoundTitle: "Ticket not found",
    ticketNotFoundMessage: "Ticket number not found! Please check your ticket and try again.",
    searchButtonLabel: "Submit",
    searchTicketLabel: "Enter your ticket number",
    searchTicketPlaceholder: "ENTER TICKET #",
    yourTicketCardTitle: "YOUR TICKET",
    yourTicketNumberLabel: "YOUR TICKET NUMBER",
    yourEstimatedWaitLabel: "YOUR ESTIMATED WAIT TIME",
    ticketsAheadOfYouLabel: "TICKETS AHEAD OF YOU",
    yourTicketPositionLabel: "YOUR TICKET'S POSITION",
    checkBackSoonValue: "CHECK BACK SOON",
    ticketNotInDrawingYetMessage: "Your ticket number is not yet in the drawing. Check back soon.",
    changeTicket: "Enter a new ticket number",
    // Arcade
    arcadeGames: "Arcade Games",
    back: "BACK",
    selectGame: "Select Game",
    snakeTitle: "Snake",
    moreGamesComing: "More Games Coming Soon",
    playSnake: "PLAY SNAKE",
    snakeInstructionMove: "USE ARROWS TO MOVE",
    snakeInstructionPoints: "EAT PELLETS FOR POINTS",
    snakeInstructionGrow: "EATING MAKES YOU GROW",
    snakeInstructionAvoid: "AVOID WALLS AND YOUR BODY",
    snakeInstructionCrash: "CRASHING ENDS THE GAME",
    playNow: "PLAY NOW",
    reset: "RESET",
    start: "START",
    play: "PLAY",
    pause: "PAUSE",
    gameOverCollision: "GAME OVER: COLLISION DETECTED",
    gameOver: "GAME OVER",
    tapToPlayAgain: "TAP HERE TO PLAY AGAIN",
    score: "SCORE",
    length: "LENGTH",
    snakeSpeedLabel: "SPEED",
    snakeDifficultyLabel: "DIFFICULTY",
    snakeSettingLabel: "SETTING",
    snakeSpeedSlow: "SLOW",
    snakeSpeedNormal: "NORMAL",
    snakeSpeedFast: "FAST",
    snakeDifficultyEasy: "EASY",
    snakeDifficultyMedium: "MEDIUM",
    snakeDifficultyHard: "HARD",
    snakeModeVeryEasy: "VERY EASY",
    snakeModeEasy: "EASY",
    snakeModeNormal: "NORMAL",
    snakeModeHard: "HARD",
    snakeModeVeryHard: "VERY HARD",
    snakeModeNightmare: "NIGHTMARE",
    gameOverAnnouncement: "Game over.",
    language: "Language",
  },
  zh: {
    nowServing: "正在叫号",
    waiting: "请等候",
    foodPantryServiceFor: "食品发放服务",
    ticketsIssuedToday: "今日号码范围",
    totalTicketsIssued: "已发号码总数",
    drawingOrder: "叫号顺序",
    updated: "更新时间",
    welcome: "欢迎！",
    raffleNotStarted: "抽签尚未开始。",
    checkBackSoon: "请稍后再查看更新。",
    pantryClosed: "今日食品分发处关闭",
    nextOpenDay: "下次开放",
    pantryHours: "食品分发时间",
    pantryNotOpenYet: "食品分发处尚未开放",
    pantryClosedForDay: "今日食品分发处已关闭",
    todaysHours: "今日营业时间",
    closed: "关闭",
    sunday: "星期日",
    monday: "星期一",
    tuesday: "星期二",
    wednesday: "星期三",
    thursday: "星期四",
    friday: "星期五",
    saturday: "星期六",
    pollingState: "正在获取最新状态…",
    refreshing: "刷新中…",
    lastChecked: "最后检查时间",
    errorLoadingState: "加载状态错误",
    unknownError: "未知错误",
    ticket: "号码",
    queuePosition: "排队位置",
    ticketsAhead: "前面等待人数",
    estimatedWait: "预计等待时间",
    notCalled: "未叫号",
    called: "已叫号",
    unclaimed: "无人认领",
    returned: "已退回",
    returnedTicketMessage: "此号码已标记为“已退回”，将不会被叫号。是您的号码吗？请告知工作人员。",
    unclaimedTicketMessage: "此号码已叫号但仍无人认领。如果这是您的号码，请签到或与工作人员联系。",
    calledAtMessage: "此号码叫号时间",
    close: "关闭",
    ticketNotFoundTitle: "找不到号码",
    ticketNotFoundMessage: "找不到该票号！请核对票据后再试。",
    searchTicketLabel: "搜索票号",
    searchTicketPlaceholder: "搜索票号 #",
    searchButtonLabel: "搜索",
    yourTicketCardTitle: "您的号码",
    yourTicketNumberLabel: "您的号码",
    yourEstimatedWaitLabel: "您的预计等待时间",
    ticketsAheadOfYouLabel: "您前面的人数",
    yourTicketPositionLabel: "您的号码位置",
    checkBackSoonValue: "请稍后再查看",
    ticketNotInDrawingYetMessage: "您的号码尚未进入叫号顺序。请稍后再查看。",
    changeTicket: "更改号码",
    // Arcade
    arcadeGames: "游戏厅",
    back: "返回",
    selectGame: "选择游戏",
    snakeTitle: "贪吃蛇",
    moreGamesComing: "更多游戏即将推出",
    playSnake: "玩贪吃蛇",
    snakeInstructionMove: "用方向键移动",
    snakeInstructionPoints: "吃食物得分",
    snakeInstructionGrow: "吃东西会变长",
    snakeInstructionAvoid: "避开墙壁和自己",
    snakeInstructionCrash: "撞到就结束",
    playNow: "开始游戏",
    reset: "重置",
    start: "开始",
    play: "继续",
    pause: "暂停",
    gameOverCollision: "游戏结束：发生碰撞",
    gameOver: "游戏结束",
    tapToPlayAgain: "点击此处重新开始",
    score: "得分",
    length: "长度",
    snakeSpeedLabel: "速度",
    snakeDifficultyLabel: "难度",
    snakeSettingLabel: "设置",
    snakeSpeedSlow: "慢",
    snakeSpeedNormal: "正常",
    snakeSpeedFast: "快",
    snakeDifficultyEasy: "简单",
    snakeDifficultyMedium: "中等",
    snakeDifficultyHard: "困难",
    snakeModeVeryEasy: "非常简单",
    snakeModeEasy: "简单",
    snakeModeNormal: "正常",
    snakeModeHard: "困难",
    snakeModeVeryHard: "非常困难",
    snakeModeNightmare: "噩梦",
    gameOverAnnouncement: "游戏结束。",
    language: "语言",
  },
  es: {
    nowServing: "Turno Actual",
    waiting: "En espera",
    foodPantryServiceFor: "Servicio del Banco de Alimentos",
    ticketsIssuedToday: "Boletos emitidos hoy",
    totalTicketsIssued: "Total de boletos emitidos",
    drawingOrder: "Orden de llamado",
    updated: "Actualizado",
    welcome: "¡Bienvenidos!",
    raffleNotStarted: "El sorteo aún no ha comenzado.",
    checkBackSoon: "Vuelva pronto para ver actualizaciones.",
    pantryClosed: "Despensa Cerrada Hoy",
    nextOpenDay: "Próxima Apertura",
    pantryHours: "Horario de Despensa",
    pantryNotOpenYet: "La Despensa Aún No Ha Abierto",
    pantryClosedForDay: "La Despensa Ha Cerrado Por Hoy",
    todaysHours: "Horario de Hoy",
    closed: "CERRADO",
    sunday: "Domingo",
    monday: "Lunes",
    tuesday: "Martes",
    wednesday: "Miércoles",
    thursday: "Jueves",
    friday: "Viernes",
    saturday: "Sábado",
    pollingState: "Consultando el estado más reciente…",
    refreshing: "Actualizando…",
    lastChecked: "Última verificación",
    errorLoadingState: "Error al cargar el estado",
    unknownError: "Error desconocido",
    ticket: "Boleto",
    queuePosition: "Posición en la Fila",
    ticketsAhead: "Personas delante",
    estimatedWait: "Espera Estimada",
    notCalled: "No llamado",
    called: "Llamado",
    unclaimed: "No reclamado",
    returned: "Devuelto",
    returnedTicketMessage:
      "Este número de boleto está marcado como \"Devuelto\" y no será llamado. ¿Es su boleto? Avise al personal sobre este problema.",
    unclaimedTicketMessage:
      "Este número de boleto ha sido llamado pero aún no se ha reclamado. Si es su boleto, haga check-in o hable con un miembro del personal.",
    calledAtMessage: "Este boleto fue llamado a las",
    close: "Cerrar",
    ticketNotFoundTitle: "Boleto no encontrado",
    ticketNotFoundMessage: "¡No se encontró el número de boleto! Verifique su boleto y vuelva a intentarlo.",
    searchTicketLabel: "Buscar número de boleto",
    searchTicketPlaceholder: "Buscar boleto #",
    searchButtonLabel: "Buscar",
    yourTicketCardTitle: "SU BOLETO",
    yourTicketNumberLabel: "SU NÚMERO DE BOLETO",
    yourEstimatedWaitLabel: "SU TIEMPO DE ESPERA ESTIMADO",
    ticketsAheadOfYouLabel: "PERSONAS DELANTE DE USTED",
    yourTicketPositionLabel: "POSICIÓN DE SU BOLETO",
    checkBackSoonValue: "VUELVA PRONTO",
    ticketNotInDrawingYetMessage: "Su número aún no está en el sorteo. Vuelva pronto.",
    changeTicket: "CAMBIAR BOLETO",
    // Arcade
    arcadeGames: "Juegos Arcade",
    back: "VOLVER",
    selectGame: "Elegir Juego",
    snakeTitle: "Serpiente",
    moreGamesComing: "Más Juegos Próximamente",
    playSnake: "JUGAR SERPIENTE",
    snakeInstructionMove: "USA LAS FLECHAS PARA MOVERTE",
    snakeInstructionPoints: "COME PARA GANAR PUNTOS",
    snakeInstructionGrow: "COMER TE HACE CRECER",
    snakeInstructionAvoid: "EVITA PAREDES Y TU CUERPO",
    snakeInstructionCrash: "CHOCAR TERMINA EL JUEGO",
    playNow: "JUGAR AHORA",
    reset: "REINICIAR",
    start: "INICIAR",
    play: "JUGAR",
    pause: "PAUSA",
    gameOverCollision: "FIN DEL JUEGO: COLISIÓN DETECTADA",
    gameOver: "FIN DEL JUEGO",
    tapToPlayAgain: "TOCA AQUÍ PARA JUGAR DE NUEVO",
    score: "PUNTOS",
    length: "LARGO",
    snakeSpeedLabel: "VELOCIDAD",
    snakeDifficultyLabel: "DIFICULTAD",
    snakeSettingLabel: "AJUSTE",
    snakeSpeedSlow: "LENTO",
    snakeSpeedNormal: "NORMAL",
    snakeSpeedFast: "RÁPIDO",
    snakeDifficultyEasy: "FÁCIL",
    snakeDifficultyMedium: "MEDIA",
    snakeDifficultyHard: "DIFÍCIL",
    snakeModeVeryEasy: "MUY FÁCIL",
    snakeModeEasy: "FÁCIL",
    snakeModeNormal: "NORMAL",
    snakeModeHard: "DIFÍCIL",
    snakeModeVeryHard: "MUY DIFÍCIL",
    snakeModeNightmare: "PESADILLA",
    gameOverAnnouncement: "Fin del juego.",
    language: "Idioma",
  },
  ru: {
    nowServing: "Вызывается номер",
    waiting: "Ожидайте",
    foodPantryServiceFor: "Раздача продуктов",
    ticketsIssuedToday: "Выданные сегодня номера",
    totalTicketsIssued: "Всего выдано билетов",
    drawingOrder: "Порядок вызова",
    updated: "Обновлено",
    welcome: "Добро пожаловать!",
    raffleNotStarted: "Розыгрыш еще не начался.",
    checkBackSoon: "Загляните позже.",
    pantryClosed: "Продовольственный склад закрыт сегодня",
    nextOpenDay: "Следующее открытие",
    pantryHours: "Часы работы склада",
    pantryNotOpenYet: "Продовольственный склад еще не открылся",
    pantryClosedForDay: "Продовольственный склад закрыт на сегодня",
    todaysHours: "Часы работы сегодня",
    closed: "ЗАКРЫТО",
    sunday: "Воскресенье",
    monday: "Понедельник",
    tuesday: "Вторник",
    wednesday: "Среда",
    thursday: "Четверг",
    friday: "Пятница",
    saturday: "Суббота",
    pollingState: "Опрос последнего состояния…",
    refreshing: "Обновление…",
    lastChecked: "Последняя проверка",
    errorLoadingState: "Ошибка загрузки состояния",
    unknownError: "Неизвестная ошибка",
    ticket: "Билет",
    queuePosition: "Место в очереди",
    ticketsAhead: "Человек впереди",
    estimatedWait: "Ориентировочное время ожидания",
    notCalled: "Не вызывался",
    called: "Вызван",
    unclaimed: "Не заявлен",
    returned: "Возвращён",
    returnedTicketMessage:
      "Этот номер билета отмечен как «Возвращён» и больше не будет вызван. Это ваш билет? Сообщите об этом сотрудникам.",
    unclaimedTicketMessage:
      "Этот номер билета был вызван, но остаётся невостребованным. Если это ваш билет, подойдите или сообщите сотрудникам.",
    calledAtMessage: "Этот билет был вызван в",
    close: "Закрыть",
    ticketNotFoundTitle: "Билет не найден",
    ticketNotFoundMessage: "Номер билета не найден! Проверьте билет и попробуйте снова.",
    searchTicketLabel: "Поиск номера билета",
    searchTicketPlaceholder: "Поиск билета #",
    searchButtonLabel: "Поиск",
    yourTicketCardTitle: "ВАШ БИЛЕТ",
    yourTicketNumberLabel: "НОМЕР ВАШЕГО БИЛЕТА",
    yourEstimatedWaitLabel: "ВАШЕ РАСЧЕТНОЕ ВРЕМЯ ОЖИДАНИЯ",
    ticketsAheadOfYouLabel: "ЛЮДЕЙ ПЕРЕД ВАМИ",
    yourTicketPositionLabel: "ПОЗИЦИЯ ВАШЕГО БИЛЕТА",
    checkBackSoonValue: "ПРОВЕРЬТЕ ПОЗЖЕ",
    ticketNotInDrawingYetMessage: "Ваш номер еще не добавлен в порядок вызова. Проверьте позже.",
    changeTicket: "ИЗМЕНИТЬ БИЛЕТ",
    // Arcade
    arcadeGames: "Аркадные Игры",
    back: "НАЗАД",
    selectGame: "Выбрать Игру",
    snakeTitle: "Змейка",
    moreGamesComing: "Скоро Больше Игр",
    playSnake: "ИГРАТЬ В ЗМЕЙКУ",
    snakeInstructionMove: "ДВИГАЙТЕСЬ СТРЕЛКАМИ",
    snakeInstructionPoints: "ЕШЬТЕ ЧТОБЫ НАБИРАТЬ ОЧКИ",
    snakeInstructionGrow: "ЕДА УВЕЛИЧИВАЕТ ДЛИНУ",
    snakeInstructionAvoid: "ИЗБЕГАЙТЕ СТЕН И СВОЕГО ТЕЛА",
    snakeInstructionCrash: "СТОЛКНОВЕНИЕ ЗАВЕРШАЕТ ИГРУ",
    playNow: "ИГРАТЬ",
    reset: "СБРОС",
    start: "СТАРТ",
    play: "ИГРАТЬ",
    pause: "ПАУЗА",
    gameOverCollision: "КОНЕЦ ИГРЫ: СТОЛКНОВЕНИЕ",
    gameOver: "КОНЕЦ ИГРЫ",
    tapToPlayAgain: "НАЖМИТЕ ЧТОБЫ ИГРАТЬ СНОВА",
    score: "ОЧКИ",
    length: "ДЛИНА",
    snakeSpeedLabel: "СКОРОСТЬ",
    snakeDifficultyLabel: "СЛОЖНОСТЬ",
    snakeSettingLabel: "РЕЖИМ",
    snakeSpeedSlow: "МЕДЛЕННО",
    snakeSpeedNormal: "НОРМАЛЬНО",
    snakeSpeedFast: "БЫСТРО",
    snakeDifficultyEasy: "ЛЕГКО",
    snakeDifficultyMedium: "СРЕДНЕ",
    snakeDifficultyHard: "СЛОЖНО",
    snakeModeVeryEasy: "ОЧЕНЬ ЛЕГКО",
    snakeModeEasy: "ЛЕГКО",
    snakeModeNormal: "НОРМАЛЬНО",
    snakeModeHard: "СЛОЖНО",
    snakeModeVeryHard: "ОЧЕНЬ СЛОЖНО",
    snakeModeNightmare: "КОШМАР",
    gameOverAnnouncement: "Конец игры.",
    language: "Язык",
  },
  uk: {
    nowServing: "Викликається номер",
    waiting: "Очікуйте",
    foodPantryServiceFor: "Роздача продуктів",
    ticketsIssuedToday: "Видані сьогодні номери",
    totalTicketsIssued: "Всього видано квитків",
    drawingOrder: "Порядок виклику",
    updated: "Оновлено",
    welcome: "Ласкаво просимо!",
    raffleNotStarted: "Розіграш ще не розпочався.",
    checkBackSoon: "Завітайте пізніше.",
    pantryClosed: "Продовольча комора сьогодні зачинена",
    nextOpenDay: "Наступне відкриття",
    pantryHours: "Години роботи комори",
    pantryNotOpenYet: "Продовольча комора ще не відкрилася",
    pantryClosedForDay: "Продовольча комора зачинена на сьогодні",
    todaysHours: "Години роботи сьогодні",
    closed: "ЗАЧИНЕНО",
    sunday: "Неділя",
    monday: "Понеділок",
    tuesday: "Вівторок",
    wednesday: "Середа",
    thursday: "Четвер",
    friday: "П'ятниця",
    saturday: "Субота",
    pollingState: "Опитування останнього стану…",
    refreshing: "Оновлення…",
    lastChecked: "Остання перевірка",
    errorLoadingState: "Помилка завантаження стану",
    unknownError: "Невідома помилка",
    ticket: "Квиток",
    queuePosition: "Місце в черзі",
    ticketsAhead: "Людей попереду",
    estimatedWait: "Орієнтовний час очікування",
    notCalled: "Не викликався",
    called: "Викликано",
    unclaimed: "Не заявлено",
    returned: "Повернуто",
    returnedTicketMessage:
      "Цей номер квитка позначено як «Повернуто» і його не викликатимуть. Це ваш квиток? Повідомте про це працівникам.",
    unclaimedTicketMessage:
      "Цей номер квитка було викликано, але він досі не заявлений. Якщо це ваш квиток, підійдіть або зверніться до працівників.",
    calledAtMessage: "Цей квиток було викликано о",
    close: "Закрити",
    ticketNotFoundTitle: "Квиток не знайдено",
    ticketNotFoundMessage: "Номер квитка не знайдено! Перевірте квиток і спробуйте ще раз.",
    searchTicketLabel: "Пошук номера квитка",
    searchTicketPlaceholder: "Пошук квитка #",
    searchButtonLabel: "Пошук",
    yourTicketCardTitle: "ВАШ КВИТОК",
    yourTicketNumberLabel: "НОМЕР ВАШОГО КВИТКА",
    yourEstimatedWaitLabel: "ВАШ РОЗРАХУНКОВИЙ ЧАС ОЧІКУВАННЯ",
    ticketsAheadOfYouLabel: "ЛЮДЕЙ ПЕРЕД ВАМИ",
    yourTicketPositionLabel: "ПОЗИЦІЯ ВАШОГО КВИТКА",
    checkBackSoonValue: "ПЕРЕВІРТЕ ПІЗНІШЕ",
    ticketNotInDrawingYetMessage: "Ваш номер ще не додано до порядку виклику. Перевірте пізніше.",
    changeTicket: "ЗМІНИТИ КВИТОК",
    // Arcade
    arcadeGames: "Аркадні Ігри",
    back: "НАЗАД",
    selectGame: "Обрати Гру",
    snakeTitle: "Змійка",
    moreGamesComing: "Скоро Більше Ігор",
    playSnake: "ГРАТИ В ЗМІЙКУ",
    snakeInstructionMove: "РУХАЙТЕСЬ СТРІЛКАМИ",
    snakeInstructionPoints: "ЇЖТЕ ЩОБ НАБИРАТИ ОЧКИ",
    snakeInstructionGrow: "ЇЖА ЗБІЛЬШУЄ ДОВЖИНУ",
    snakeInstructionAvoid: "УНИКАЙТЕ СТІН І СВОГО ТІЛА",
    snakeInstructionCrash: "ЗІТКНЕННЯ ЗАВЕРШУЄ ГРУ",
    playNow: "ГРАТИ",
    reset: "СКИДАННЯ",
    start: "СТАРТ",
    play: "ГРАТИ",
    pause: "ПАУЗА",
    gameOverCollision: "КІНЕЦЬ ГРИ: ЗІТКНЕННЯ",
    gameOver: "КІНЕЦЬ ГРИ",
    tapToPlayAgain: "НАТИСНІТЬ ЩОБ ГРАТИ ЗНОВУ",
    score: "ОЧКИ",
    length: "ДОВЖИНА",
    snakeSpeedLabel: "ШВИДКІСТЬ",
    snakeDifficultyLabel: "СКЛАДНІСТЬ",
    snakeSettingLabel: "РЕЖИМ",
    snakeSpeedSlow: "ПОВІЛЬНО",
    snakeSpeedNormal: "НОРМАЛЬНО",
    snakeSpeedFast: "ШВИДКО",
    snakeDifficultyEasy: "ЛЕГКО",
    snakeDifficultyMedium: "СЕРЕДНЬО",
    snakeDifficultyHard: "ВАЖКО",
    snakeModeVeryEasy: "ДУЖЕ ЛЕГКО",
    snakeModeEasy: "ЛЕГКО",
    snakeModeNormal: "НОРМАЛЬНО",
    snakeModeHard: "ВАЖКО",
    snakeModeVeryHard: "ДУЖЕ ВАЖКО",
    snakeModeNightmare: "КОШМАР",
    gameOverAnnouncement: "Кінець гри.",
    language: "Мова",
  },
  vi: {
    nowServing: "Đang gọi số",
    waiting: "Vui lòng chờ",
    foodPantryServiceFor: "Phát thực phẩm ngày",
    ticketsIssuedToday: "Số vé phát hôm nay",
    totalTicketsIssued: "Tổng số vé đã phát",
    drawingOrder: "Thứ tự bốc thăm",
    updated: "Cập nhật",
    welcome: "Chào mừng!",
    raffleNotStarted: "Chưa bắt đầu bốc thăm.",
    checkBackSoon: "Vui lòng quay lại sau.",
    pantryClosed: "Kho Thực Phẩm Đóng Cửa Hôm Nay",
    nextOpenDay: "Mở Cửa Tiếp Theo",
    pantryHours: "Giờ Mở Cửa",
    pantryNotOpenYet: "Kho Thực Phẩm Chưa Mở Cửa",
    pantryClosedForDay: "Kho Thực Phẩm Đã Đóng Cửa Hôm Nay",
    todaysHours: "Giờ Hôm Nay",
    closed: "ĐÓNG CỬA",
    sunday: "Chủ Nhật",
    monday: "Thứ Hai",
    tuesday: "Thứ Ba",
    wednesday: "Thứ Tư",
    thursday: "Thứ Năm",
    friday: "Thứ Sáu",
    saturday: "Thứ Bảy",
    pollingState: "Đang tải trạng thái mới nhất…",
    refreshing: "Đang làm mới…",
    lastChecked: "Kiểm tra lần cuối",
    errorLoadingState: "Lỗi tải trạng thái",
    unknownError: "Lỗi không xác định",
    ticket: "Vé",
    queuePosition: "Vị trí trong hàng",
    ticketsAhead: "Số người phía trước",
    estimatedWait: "Thời gian chờ dự kiến",
    notCalled: "Chưa gọi",
    called: "Đã gọi",
    unclaimed: "Chưa nhận",
    returned: "Đã trả",
    returnedTicketMessage:
      "Số vé này được đánh dấu \"Đã trả\" và sẽ không được gọi. Đây có phải vé của bạn không? Vui lòng báo cho nhân viên.",
    unclaimedTicketMessage:
      "Số vé này đã được gọi nhưng vẫn chưa được nhận. Nếu đây là vé của bạn, vui lòng check-in hoặc nói với nhân viên.",
    calledAtMessage: "Số vé này được gọi lúc",
    close: "Đóng",
    ticketNotFoundTitle: "Không tìm thấy vé",
    ticketNotFoundMessage: "Không tìm thấy số vé! Vui lòng kiểm tra vé và thử lại.",
    searchTicketLabel: "Tìm số vé",
    searchTicketPlaceholder: "Tìm vé #",
    searchButtonLabel: "Tìm",
    yourTicketCardTitle: "VÉ CỦA BẠN",
    yourTicketNumberLabel: "SỐ VÉ CỦA BẠN",
    yourEstimatedWaitLabel: "THỜI GIAN CHỜ DỰ KIẾN CỦA BẠN",
    ticketsAheadOfYouLabel: "SỐ NGƯỜI PHÍA TRƯỚC BẠN",
    yourTicketPositionLabel: "VỊ TRÍ VÉ CỦA BẠN",
    checkBackSoonValue: "QUAY LẠI SAU",
    ticketNotInDrawingYetMessage: "Số của bạn chưa có trong thứ tự bốc thăm. Vui lòng quay lại sau.",
    changeTicket: "ĐỔI VÉ",
    // Arcade
    arcadeGames: "Trò Chơi Điện Tử",
    back: "QUAY LẠI",
    selectGame: "Chọn Trò Chơi",
    snakeTitle: "Rắn Săn Mồi",
    moreGamesComing: "Sắp Có Thêm Trò Chơi",
    playSnake: "CHƠI RẮN SĂN MỒI",
    snakeInstructionMove: "DÙNG PHÍM MŨI TÊN ĐỂ DI CHUYỂN",
    snakeInstructionPoints: "ĂN ĐỂ GIAO ĐIỂM",
    snakeInstructionGrow: "ĂN SẼ LÀM BẠN DÀI RA",
    snakeInstructionAvoid: "TRÁNH TƯỜNG VÀ THÂN MÌNH",
    snakeInstructionCrash: "VA CHẠM SẼ KẾT THÚC TRÒ CHƠI",
    playNow: "CHƠI NGAY",
    reset: "ĐẶT LẠI",
    start: "BẮT ĐẦU",
    play: "CHƠI",
    pause: "TẠM DỪNG",
    gameOverCollision: "THUA: VA CHẠM",
    gameOver: "THUA RỒI",
    tapToPlayAgain: "CHẠM ĐÂY ĐỂ CHƠI LẠI",
    score: "ĐIỂM",
    length: "ĐỘ DÀI",
    snakeSpeedLabel: "TỐC ĐỘ",
    snakeDifficultyLabel: "ĐỘ KHÓ",
    snakeSettingLabel: "CHẾ ĐỘ",
    snakeSpeedSlow: "CHẬM",
    snakeSpeedNormal: "BÌNH THƯỜNG",
    snakeSpeedFast: "NHANH",
    snakeDifficultyEasy: "DỄ",
    snakeDifficultyMedium: "TRUNG BÌNH",
    snakeDifficultyHard: "KHÓ",
    snakeModeVeryEasy: "RẤT DỄ",
    snakeModeEasy: "DỄ",
    snakeModeNormal: "BÌNH THƯỜNG",
    snakeModeHard: "KHÓ",
    snakeModeVeryHard: "RẤT KHÓ",
    snakeModeNightmare: "ÁC MỘNG",
    gameOverAnnouncement: "Trò chơi kết thúc.",
    language: "Ngôn Ngữ",
  },
  fa: {
    nowServing: "در حال فراخوانی شماره",
    waiting: "لطفاً صبر کنید",
    foodPantryServiceFor: "توزیع مواد غذایی برای",
    ticketsIssuedToday: "بلیط‌های صادر شده امروز",
    totalTicketsIssued: "مجموع بلیط‌های صادر شده",
    drawingOrder: "ترتیب قرعه‌کشی",
    updated: "به‌روزرسانی",
    welcome: "خوش آمدید!",
    raffleNotStarted: "قرعه‌کشی هنوز شروع نشده است.",
    checkBackSoon: "لطفاً بعداً مراجعه کنید.",
    pantryClosed: "انبار غذا امروز بسته است",
    nextOpenDay: "باز شدن بعدی",
    pantryHours: "ساعات کار انبار",
    pantryNotOpenYet: "انبار غذا هنوز باز نشده است",
    pantryClosedForDay: "انبار غذا برای امروز بسته شده است",
    todaysHours: "ساعات امروز",
    closed: "بسته",
    sunday: "یکشنبه",
    monday: "دوشنبه",
    tuesday: "سه‌شنبه",
    wednesday: "چهارشنبه",
    thursday: "پنج‌شنبه",
    friday: "جمعه",
    saturday: "شنبه",
    pollingState: "در حال دریافت آخرین وضعیت…",
    refreshing: "در حال به‌روزرسانی…",
    lastChecked: "آخرین بررسی",
    errorLoadingState: "خطا در بارگذاری وضعیت",
    unknownError: "خطای ناشناخته",
    ticket: "بلیط",
    queuePosition: "جایگاه در صف",
    ticketsAhead: "نفر جلوتر",
    estimatedWait: "زمان انتظار تقریبی",
    notCalled: "فراخوانی نشده",
    called: "فراخوانی شده",
    unclaimed: "تحویل‌نشده",
    returned: "برگشت داده شده",
    returnedTicketMessage:
      "این شماره بلیط به عنوان «برگشت داده شده» علامت‌گذاری شده و دیگر فراخوانی نمی‌شود. اگر این بلیط شماست، لطفاً به کارکنان اطلاع دهید.",
    unclaimedTicketMessage:
      "این شماره بلیط فراخوانی شده اما هنوز تحویل نشده است. اگر این بلیط شماست، لطفاً مراجعه کنید یا با کارکنان صحبت کنید.",
    calledAtMessage: "این بلیط در ساعت",
    close: "بستن",
    ticketNotFoundTitle: "بلیط پیدا نشد",
    ticketNotFoundMessage: "شماره بلیط پیدا نشد! لطفاً بلیط خود را بررسی کرده و دوباره تلاش کنید.",
    searchTicketLabel: "جستجوی شماره بلیط",
    searchTicketPlaceholder: "# جستجوی بلیط",
    searchButtonLabel: "جستجو",
    yourTicketCardTitle: "بلیط شما",
    yourTicketNumberLabel: "شماره بلیط شما",
    yourEstimatedWaitLabel: "زمان انتظار تقریبی شما",
    ticketsAheadOfYouLabel: "تعداد افراد جلوتر از شما",
    yourTicketPositionLabel: "موقعیت بلیط شما",
    checkBackSoonValue: "بعداً دوباره بررسی کنید",
    ticketNotInDrawingYetMessage: "شماره شما هنوز وارد ترتیب قرعه‌کشی نشده است. لطفاً بعداً بررسی کنید.",
    changeTicket: "تغییر بلیط",
    // Arcade
    arcadeGames: "بازی‌های آرکید",
    back: "بازگشت",
    selectGame: "انتخاب بازی",
    snakeTitle: "مار",
    moreGamesComing: "بازی‌های بیشتر به‌زودی",
    playSnake: "بازی مار",
    snakeInstructionMove: "با کلیدهای جهت‌دار حرکت کنید",
    snakeInstructionPoints: "برای امتیاز بخورید",
    snakeInstructionGrow: "خوردن شما را بزرگ‌تر می‌کند",
    snakeInstructionAvoid: "از دیوارها و بدن خود دوری کنید",
    snakeInstructionCrash: "برخورد بازی را تمام می‌کند",
    playNow: "شروع بازی",
    reset: "بازنشانی",
    start: "شروع",
    play: "ادامه",
    pause: "مکث",
    gameOverCollision: "باخت: برخورد",
    gameOver: "باخت",
    tapToPlayAgain: "برای بازی دوباره اینجا بزنید",
    score: "امتیاز",
    length: "طول",
    snakeSpeedLabel: "سرعت",
    snakeDifficultyLabel: "درجه سختی",
    snakeSettingLabel: "حالت",
    snakeSpeedSlow: "کند",
    snakeSpeedNormal: "معمولی",
    snakeSpeedFast: "سریع",
    snakeDifficultyEasy: "آسان",
    snakeDifficultyMedium: "متوسط",
    snakeDifficultyHard: "سخت",
    snakeModeVeryEasy: "خیلی آسان",
    snakeModeEasy: "آسان",
    snakeModeNormal: "معمولی",
    snakeModeHard: "سخت",
    snakeModeVeryHard: "خیلی سخت",
    snakeModeNightmare: "کابوس",
    gameOverAnnouncement: "بازی تمام شد.",
    language: "زبان",
  },
  ar: {
    nowServing: "الرقم الحالي",
    waiting: "يرجى الانتظار",
    foodPantryServiceFor: "توزيع المواد الغذائية ليوم",
    ticketsIssuedToday: "التذاكر الصادرة اليوم",
    totalTicketsIssued: "إجمالي التذاكر الصادرة",
    drawingOrder: "ترتيب السحب",
    updated: "تم التحديث",
    welcome: "أهلاً وسهلاً!",
    raffleNotStarted: "لم تبدأ القرعة بعد.",
    checkBackSoon: "يرجى العودة لاحقاً.",
    pantryClosed: "المخزن مغلق اليوم",
    nextOpenDay: "الافتتاح القادم",
    pantryHours: "ساعات المخزن",
    pantryNotOpenYet: "المخزن لم يفتح بعد",
    pantryClosedForDay: "المخزن مغلق لهذا اليوم",
    todaysHours: "ساعات اليوم",
    closed: "مغلق",
    sunday: "الأحد",
    monday: "الاثنين",
    tuesday: "الثلاثاء",
    wednesday: "الأربعاء",
    thursday: "الخميس",
    friday: "الجمعة",
    saturday: "السبت",
    pollingState: "جارٍ تحميل أحدث البيانات…",
    refreshing: "جارٍ التحديث…",
    lastChecked: "آخر فحص",
    errorLoadingState: "خطأ في تحميل الحالة",
    unknownError: "خطأ غير معروف",
    ticket: "تذكرة",
    queuePosition: "الموقع في الطابور",
    ticketsAhead: "أشخاص أمامك",
    estimatedWait: "وقت الانتظار المتوقع",
    notCalled: "لم يُنادى",
    called: "تم النداء",
    unclaimed: "غير مطالب به",
    returned: "مُعاد",
    returnedTicketMessage:
      "تم وضع علامة \"مُعاد\" على رقم التذكرة هذا ولن يتم النداء عليه. هل هذه تذكرتك؟ يرجى إبلاغ الموظفين بهذه المشكلة.",
    unclaimedTicketMessage:
      "تم النداء على رقم التذكرة هذا لكنه لا يزال غير مطالب به. إذا كانت هذه تذكرتك، يرجى تسجيل الحضور أو التحدث مع أحد الموظفين.",
    calledAtMessage: "تم النداء على هذه التذكرة في",
    close: "إغلاق",
    ticketNotFoundTitle: "لم يتم العثور على التذكرة",
    ticketNotFoundMessage: "لم يتم العثور على رقم التذكرة! يرجى التحقق من التذكرة والمحاولة مرة أخرى.",
    searchTicketLabel: "ابحث عن رقم التذكرة",
    searchTicketPlaceholder: "# ابحث عن تذكرة",
    searchButtonLabel: "بحث",
    yourTicketCardTitle: "تذكرتك",
    yourTicketNumberLabel: "رقم تذكرتك",
    yourEstimatedWaitLabel: "وقت الانتظار المتوقع لك",
    ticketsAheadOfYouLabel: "عدد الأشخاص أمامك",
    yourTicketPositionLabel: "موضع تذكرتك",
    checkBackSoonValue: "تحقق قريبًا",
    ticketNotInDrawingYetMessage: "رقمك ليس ضمن ترتيب السحب بعد. يرجى التحقق لاحقًا.",
    changeTicket: "تغيير التذكرة",
    // Arcade
    arcadeGames: "ألعاب أركيد",
    back: "رجوع",
    selectGame: "اختر لعبة",
    snakeTitle: "الأفعى",
    moreGamesComing: "المزيد من الألعاب قريباً",
    playSnake: "العب الأفعى",
    snakeInstructionMove: "استخدم الأسهم للتحرك",
    snakeInstructionPoints: "كل لكسب النقاط",
    snakeInstructionGrow: "الأكل يجعلك تكبر",
    snakeInstructionAvoid: "تجنب الجدران وجسمك",
    snakeInstructionCrash: "الاصطدام ينهي اللعبة",
    playNow: "العب الآن",
    reset: "إعادة ضبط",
    start: "ابدأ",
    play: "العب",
    pause: "إيقاف مؤقت",
    gameOverCollision: "انتهت اللعبة: اصطدام",
    gameOver: "انتهت اللعبة",
    tapToPlayAgain: "انقر هنا للعب مرة أخرى",
    score: "النقاط",
    length: "الطول",
    snakeSpeedLabel: "السرعة",
    snakeDifficultyLabel: "الصعوبة",
    snakeSettingLabel: "الإعداد",
    snakeSpeedSlow: "بطيء",
    snakeSpeedNormal: "عادي",
    snakeSpeedFast: "سريع",
    snakeDifficultyEasy: "سهل",
    snakeDifficultyMedium: "متوسط",
    snakeDifficultyHard: "صعب",
    snakeModeVeryEasy: "سهل جدًا",
    snakeModeEasy: "سهل",
    snakeModeNormal: "عادي",
    snakeModeHard: "صعب",
    snakeModeVeryHard: "صعب جدًا",
    snakeModeNightmare: "كابوس",
    gameOverAnnouncement: "انتهت اللعبة.",
    language: "اللغة",
  },
};
