"use client";

import React from "react";

export type Language = "en" | "zh" | "es" | "ru" | "uk" | "vi" | "fa" | "ar";

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
};

const LanguageContext = React.createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = React.useState<Language>("en");

  React.useEffect(() => {
    const stored = typeof window !== "undefined" ? localStorage.getItem("display-language") : null;
    if (stored && ["en", "zh", "es", "ru", "uk", "vi", "fa", "ar"].includes(stored)) {
      setLanguageState(stored as Language);
    }
  }, []);

  const setLanguage = React.useCallback((lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== "undefined") {
      localStorage.setItem("display-language", lang);
    }
  }, []);

  const t = React.useCallback(
    (key: string) => translations[language]?.[key] ?? translations.en[key] ?? key,
    [language],
  );

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = React.useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    nowServing: "Now Serving",
    waiting: "Pending",
    foodPantryServiceFor: "Food Pantry Service For",
    ticketsIssuedToday: "Tickets Issued Today",
    totalTicketsIssued: "Total Tickets Issued",
    drawingOrder: "Drawing Order",
    updated: "Updated",
    welcome: "Welcome!",
    raffleNotStarted: "The raffle has not yet started.",
    checkBackSoon: "Check back soon for updates.",
    pantryClosed: "Pantry Closed Today",
    nextOpenDay: "Next Open",
    pantryHours: "Pantry Hours",
    sunday: "Sunday",
    monday: "Monday",
    tuesday: "Tuesday",
    wednesday: "Wednesday",
    thursday: "Thursday",
    friday: "Friday",
    saturday: "Saturday",
    pollingState: "Polling for latest state…",
    refreshing: "Refreshing…",
    lastChecked: "Last checked",
    errorLoadingState: "Error loading state",
    unknownError: "Unknown error",
    ticket: "Ticket",
    queuePosition: "Queue Position",
    ticketsAhead: "Tickets Ahead",
    estimatedWait: "Estimated Wait",
    close: "Close",
  },
  zh: {
    nowServing: "正在叫号",
    waiting: "请等候",
    foodPantryServiceFor: "食品发放服务",
    ticketsIssuedToday: "今日号码范围",
    totalTicketsIssued: "已发号码总数",
    drawingOrder: "叫号顺序",
    updated: "更新时间",
    welcome: "欢迎！",
    raffleNotStarted: "抽签尚未开始。",
    checkBackSoon: "请稍后再查看更新。",
    pantryClosed: "今日食品分发处关闭",
    nextOpenDay: "下次开放",
    pantryHours: "食品分发时间",
    sunday: "星期日",
    monday: "星期一",
    tuesday: "星期二",
    wednesday: "星期三",
    thursday: "星期四",
    friday: "星期五",
    saturday: "星期六",
    pollingState: "正在获取最新状态…",
    refreshing: "刷新中…",
    lastChecked: "最后检查时间",
    errorLoadingState: "加载状态错误",
    unknownError: "未知错误",
    ticket: "号码",
    queuePosition: "排队位置",
    ticketsAhead: "前面等待人数",
    estimatedWait: "预计等待时间",
    close: "关闭",
  },
  es: {
    nowServing: "Turno Actual",
    waiting: "En espera",
    foodPantryServiceFor: "Servicio del Banco de Alimentos",
    ticketsIssuedToday: "Boletos emitidos hoy",
    totalTicketsIssued: "Total de boletos emitidos",
    drawingOrder: "Orden de llamado",
    updated: "Actualizado",
    welcome: "¡Bienvenidos!",
    raffleNotStarted: "El sorteo aún no ha comenzado.",
    checkBackSoon: "Vuelva pronto para ver actualizaciones.",
    pantryClosed: "Despensa Cerrada Hoy",
    nextOpenDay: "Próxima Apertura",
    pantryHours: "Horario de Despensa",
    sunday: "Domingo",
    monday: "Lunes",
    tuesday: "Martes",
    wednesday: "Miércoles",
    thursday: "Jueves",
    friday: "Viernes",
    saturday: "Sábado",
    pollingState: "Consultando el estado más reciente…",
    refreshing: "Actualizando…",
    lastChecked: "Última verificación",
    errorLoadingState: "Error al cargar el estado",
    unknownError: "Error desconocido",
    ticket: "Boleto",
    queuePosition: "Posición en la Fila",
    ticketsAhead: "Personas delante",
    estimatedWait: "Espera Estimada",
    close: "Cerrar",
  },
  ru: {
    nowServing: "Вызывается номер",
    waiting: "Ожидайте",
    foodPantryServiceFor: "Раздача продуктов",
    ticketsIssuedToday: "Выданные сегодня номера",
    totalTicketsIssued: "Всего выдано билетов",
    drawingOrder: "Порядок вызова",
    updated: "Обновлено",
    welcome: "Добро пожаловать!",
    raffleNotStarted: "Розыгрыш еще не начался.",
    checkBackSoon: "Загляните позже.",
    pantryClosed: "Продовольственный склад закрыт сегодня",
    nextOpenDay: "Следующее открытие",
    pantryHours: "Часы работы склада",
    sunday: "Воскресенье",
    monday: "Понедельник",
    tuesday: "Вторник",
    wednesday: "Среда",
    thursday: "Четверг",
    friday: "Пятница",
    saturday: "Суббота",
    pollingState: "Опрос последнего состояния…",
    refreshing: "Обновление…",
    lastChecked: "Последняя проверка",
    errorLoadingState: "Ошибка загрузки состояния",
    unknownError: "Неизвестная ошибка",
    ticket: "Билет",
    queuePosition: "Место в очереди",
    ticketsAhead: "Человек впереди",
    estimatedWait: "Ориентировочное время ожидания",
    close: "Закрыть",
  },
  uk: {
    nowServing: "Викликається номер",
    waiting: "Очікуйте",
    foodPantryServiceFor: "Роздача продуктів",
    ticketsIssuedToday: "Видані сьогодні номери",
    totalTicketsIssued: "Всього видано квитків",
    drawingOrder: "Порядок виклику",
    updated: "Оновлено",
    welcome: "Ласкаво просимо!",
    raffleNotStarted: "Розіграш ще не розпочався.",
    checkBackSoon: "Завітайте пізніше.",
    pantryClosed: "Продовольча комора сьогодні зачинена",
    nextOpenDay: "Наступне відкриття",
    pantryHours: "Години роботи комори",
    sunday: "Неділя",
    monday: "Понеділок",
    tuesday: "Вівторок",
    wednesday: "Середа",
    thursday: "Четвер",
    friday: "П'ятниця",
    saturday: "Субота",
    pollingState: "Опитування останнього стану…",
    refreshing: "Оновлення…",
    lastChecked: "Остання перевірка",
    errorLoadingState: "Помилка завантаження стану",
    unknownError: "Невідома помилка",
    ticket: "Квиток",
    queuePosition: "Місце в черзі",
    ticketsAhead: "Людей попереду",
    estimatedWait: "Орієнтовний час очікування",
    close: "Закрити",
  },
  vi: {
    nowServing: "Đang gọi số",
    waiting: "Vui lòng chờ",
    foodPantryServiceFor: "Phát thực phẩm ngày",
    ticketsIssuedToday: "Số vé phát hôm nay",
    totalTicketsIssued: "Tổng số vé đã phát",
    drawingOrder: "Thứ tự bốc thăm",
    updated: "Cập nhật",
    welcome: "Chào mừng!",
    raffleNotStarted: "Chưa bắt đầu bốc thăm.",
    checkBackSoon: "Vui lòng quay lại sau.",
    pantryClosed: "Kho Thực Phẩm Đóng Cửa Hôm Nay",
    nextOpenDay: "Mở Cửa Tiếp Theo",
    pantryHours: "Giờ Mở Cửa",
    sunday: "Chủ Nhật",
    monday: "Thứ Hai",
    tuesday: "Thứ Ba",
    wednesday: "Thứ Tư",
    thursday: "Thứ Năm",
    friday: "Thứ Sáu",
    saturday: "Thứ Bảy",
    pollingState: "Đang tải trạng thái mới nhất…",
    refreshing: "Đang làm mới…",
    lastChecked: "Kiểm tra lần cuối",
    errorLoadingState: "Lỗi tải trạng thái",
    unknownError: "Lỗi không xác định",
    ticket: "Vé",
    queuePosition: "Vị trí trong hàng",
    ticketsAhead: "Số người phía trước",
    estimatedWait: "Thời gian chờ dự kiến",
    close: "Đóng",
  },
  fa: {
    nowServing: "در حال فراخوانی شماره",
    waiting: "لطفاً صبر کنید",
    foodPantryServiceFor: "توزیع مواد غذایی برای",
    ticketsIssuedToday: "بلیط‌های صادر شده امروز",
    totalTicketsIssued: "مجموع بلیط‌های صادر شده",
    drawingOrder: "ترتیب قرعه‌کشی",
    updated: "به‌روزرسانی",
    welcome: "خوش آمدید!",
    raffleNotStarted: "قرعه‌کشی هنوز شروع نشده است.",
    checkBackSoon: "لطفاً بعداً مراجعه کنید.",
    pantryClosed: "انبار غذا امروز بسته است",
    nextOpenDay: "باز شدن بعدی",
    pantryHours: "ساعات کار انبار",
    sunday: "یکشنبه",
    monday: "دوشنبه",
    tuesday: "سه‌شنبه",
    wednesday: "چهارشنبه",
    thursday: "پنج‌شنبه",
    friday: "جمعه",
    saturday: "شنبه",
    pollingState: "در حال دریافت آخرین وضعیت…",
    refreshing: "در حال به‌روزرسانی…",
    lastChecked: "آخرین بررسی",
    errorLoadingState: "خطا در بارگذاری وضعیت",
    unknownError: "خطای ناشناخته",
    ticket: "بلیط",
    queuePosition: "جایگاه در صف",
    ticketsAhead: "نفر جلوتر",
    estimatedWait: "زمان انتظار تقریبی",
    close: "بستن",
  },
  ar: {
    nowServing: "الرقم الحالي",
    waiting: "يرجى الانتظار",
    foodPantryServiceFor: "توزيع المواد الغذائية ليوم",
    ticketsIssuedToday: "التذاكر الصادرة اليوم",
    totalTicketsIssued: "إجمالي التذاكر الصادرة",
    drawingOrder: "ترتيب السحب",
    updated: "تم التحديث",
    welcome: "أهلاً وسهلاً!",
    raffleNotStarted: "لم تبدأ القرعة بعد.",
    checkBackSoon: "يرجى العودة لاحقاً.",
    pantryClosed: "المخزن مغلق اليوم",
    nextOpenDay: "الافتتاح القادم",
    pantryHours: "ساعات المخزن",
    sunday: "الأحد",
    monday: "الاثنين",
    tuesday: "الثلاثاء",
    wednesday: "الأربعاء",
    thursday: "الخميس",
    friday: "الجمعة",
    saturday: "السبت",
    pollingState: "جارٍ تحميل أحدث البيانات…",
    refreshing: "جارٍ التحديث…",
    lastChecked: "آخر فحص",
    errorLoadingState: "خطأ في تحميل الحالة",
    unknownError: "خطأ غير معروف",
    ticket: "تذكرة",
    queuePosition: "الموقع في الطابور",
    ticketsAhead: "أشخاص أمامك",
    estimatedWait: "وقت الانتظار المتوقع",
    close: "إغلاق",
  },
};
